### ISSUE TITLE
请教个gradle的问题

### ISSUE THREAD

**Issue by sweet2o09** [CodingCodersCode/EvolvingNetLib#1]
下面这个代码是什么意思?
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.+'
            }
        }
    }
}

**Comment by CodingCodersCode** [comment]
可以查看以下链接，以获取更详细介绍
http://www.jcodecraeer.com/a/anzhuokaifa/androidkaifa/2017/0910/8491.html
或
http://blog.csdn.net/maosidiaoxian/article/details/53616326
